In [1]:
import numpy as np

In [2]:
l=['sudh',1,2,3,4]

In [3]:
type(l)

list

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
a1=np.array([3,4,5,6,3.0])

In [6]:
a=np.array([[1,2],[3,4]])

In [7]:
a

array([[1, 2],
       [3, 4]])

In [8]:
a[1][1]

4

In [9]:
a2=np.array([1,2,3,4],ndmin=4)

In [10]:
a2

array([[[[1, 2, 3, 4]]]])

In [11]:
a2[0][0][0][0]

1

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [15]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [16]:
np.asanyarray()

TypeError: asanyarray() missing 1 required positional argument: 'a'

In [17]:
a=[1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [18]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [19]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [20]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
np.fromfunction(lambda i,j,z,p:i*j*z*p ,(4,3,2,2),dtype=int )

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [26]:
a=np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2),dtype=int )

In [27]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [31]:
a.reshape(2,4,-54)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [29]:
a.ndim

3

In [32]:
a.size

24

In [33]:
a.shape

(4, 3, 2)

In [34]:
a.dtype

dtype('int32')